name: Welcome New Contributors

on:
  pull_request_target:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login != github.repository_owner
    steps:
      - name: Greet the contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
          
            👋 Hello, and thanks for opening your first pull request!  
            We appreciate your contribution to our music player project.  
            Be sure to follow our contribution guidelines and have fun coding! 🎵
